name: social_network
description: Pet project on the topic of social networks.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_bloc: ^1.0.0
  cached_network_image: ^2.0.0-rc.1
  flutter_cache_manager: ^1.1.3
  path_provider: ^1.5.1
  snappable: ^1.0.1
  expandable: ^4.0.2
  flutter_spinkit: ^4.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter:
  uses-material-design: true
  assets:
    - assets/test-avatar/
    - assets/flare/
    - assets/localizations/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "res/icon_panda.png"